# Site settings
title: matbaj Blog
header-img: img/home-bg.jpg
email: 
description: "matbaj techlog"
baseurl: 
url: "http://matbaj.github.io/"
twitter_username: matbaj
github_username:  matbaj
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
